# https://github.com/realm/SwiftLint?tab=readme-ov-file#configuration
# By default, SwiftLint uses a set of sensible default rules you can adjust:
#disabled_rules: # rule identifiers turned on by default to exclude from running
#    - trailing_whitespace
#    - trailing_newline
#    - vertical_whitespace
